spring.application.name=pandit
#spring.profiles.active=local

spring.datasource.url = jdbc:postgresql://dpg-d6itkjjh46gs73ac9kig-a/pandits
spring.datasource.username = pandits_user
spring.datasource.password = zhHAtIC6nmUCtwIgyPHDiS5HelmVm1XA
spring.jpa.hibernate.ddl-auto = none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

