spring.application.name=pandit

spring.datasource.url = jdbc:postgresql://localhost:5432/pandit?currentSchema=public
spring.datasource.username = postgres
spring.datasource.password = root
spring.jpa.hibernate.ddl-auto = update
